### ISSUE TITLE
ability to specify "rename" policy if existing content matches

### ISSUE THREAD

**Issue by frapell** [collective/plone.importexport#2]
Original issue: https://github.com/Shriyanshagro/plone.importexport/issues/7

It would be good to have functionality which would allow user to rename the object id while importing if the object with the same id already existing.

This functionality is near to completion, all it takes to [integrate it into UI using JS script](https://github.com/collective/plone.importexport/blob/master/src/plone/importexport/browser/static/import_export.js#L117). The python functions to [support this functionality is already in place](https://github.com/collective/plone.importexport/blob/master/src/plone/importexport/browser/importexport.py#L319).

**Comment by djay** [comment]
Probably needs a "On Existing" option with [skip, update, rename, stop] options

**Comment by djay** [comment]
I think this is covered in #9
