### ISSUE TITLE
Unittests are failing

### ISSUE THREAD

**Issue by b4oshany** [collective/plone.importexport#36]
One of the main reason why the unittests are failing is due to the fact that the [ImportExportTest.zip](https://github.com/collective/plone.importexport/tree/master/src/plone/importexport/tests) is corrupted and cannot be extracted during the various [tests cases]((https://github.com/collective/plone.importexport/blob/master/src/plone/importexport/tests/test_importexport.py#L24)). Fix the corrupted zip file or rebuild the structure of the zip file by hardcoding it.

**Comment by ironmaniiith** [comment]
It got corrupted [here](https://github.com/collective/plone.importexport/commits/c67f183f4ac9208dad25aefc972153bf73a95044/src/plone/importexport/tests/ImportExportTest.zip). I tried the previous commit by @Shriyanshagro where the zip file worked fine.

**Comment by Shriyanshagro** [comment]
This issue has been moved to #42
