### ISSUE TITLE
Common coding practises

### ISSUE THREAD

**Issue by ironmaniiith** [collective/plone.importexport#39]
I see a lot of places where things like type of quote (single, double), type of case (underscore_case, camelCase) for methods, functions or classes etc. are not uniformly followed. What are the common coding practises followed in plone projects? I'll just refactor the code accordingly as I'm browsing through it and will make sure to make these things consistent throughout during the later development phase.

**Comment by djay** [comment]
you will see in other plone plugins a code analysis plugin which sets a git commit hook. Some use it, some don’t. But if you do use it you want to have one big commit to clean up existing code in one go and then merge it quick.
