### ISSUE TITLE
Export story 2 - Export documents whose title contains a particular keyword

### ISSUE THREAD

**Issue by ironmaniiith** [collective/plone.importexport#56]
**Description**:

As an admin I can go to site setup, filter out the documents(pages) based on a specific word that’s present in its titles. I can obtain all these pages as a zip with CSV metadata.

**User scenario**

1. Fred goes to site setup looking for an export section. Fred wishes to export all the pages which are corresponding to any documentation

2. Fred uses the **query widget**, select the criteria as “**Type**”

3. As type, Fred choses “**Page**”

4. Fred selects **combined** under **Format for performing export**, which enables him to get actual images and the metadata associated with it.

5. Again Fred uses the query widget and filter out his previous results based on the titles that contains “doc” in it. For this, he selects the type as "Title" in widget query, and types "doc"

6. Fred starts the export action by clicking on the export button.

7. When the action is completed he obtains a zip file along with the metadata csv file. He obtains all the documentation pages that were present in his site which he verified after extracting the zip file

8. Fred can save these documentations locally, upload to any other portal as well whenever required

Demo video: [link](https://drive.google.com/open?id=1jM0-E80IdG8YOjJVaFa-Wco9Lk3qwNEg)

Screenshot:
![image](https://user-images.githubusercontent.com/9266422/60275691-f24de700-9917-11e9-8b15-494134d66031.png)

**Comment by djay** [comment]
merged with https://github.com/collective/plone.importexport/issues/55
