### ISSUE TITLE
Export story 3 - Export titles of all pages in sorted order

### ISSUE THREAD

**Issue by ironmaniiith** [collective/plone.importexport#57]
**Description**

As an admin I can go to site setup, download a zip file which contains all the titles of the pages in my site in csv format. I can be sure that the csv file that I obtain for all the pages is having all the entries in **sorted order** based on the **title** which makes it easier and comfortable for viewing files/folders entries in the metadata as well.

**User scenario**

1. Fred goes to site setup looking for an export section. 

2. Fred uses the query widget to select the criteria as “**Type**”.

3. As type, Fred choses “**Page**”

4. Since Fred wants to have only the metadata, he selects csv under the section of "**Format for performing export**".

5. Fred also wants only the **titles** to be present in sorted order in metadata. For this he selects title in the metadata section.

6. Fred clicks on the export button and the export operation begins.

7. Fred downloads the zip file. The zip file only contains a csv. Fred expects the csv file to contain title of all the pages (in sorted order). He finds that the all titles indeed are in the sorted order

Demo video: [link](https://drive.google.com/open?id=1S3Z071oHi-U-bjFKOz4scuxywdwC8akF)

Screenshot:
![image](https://user-images.githubusercontent.com/9266422/60281015-b91a7480-9921-11e9-8ee7-61a63d433f0f.png)

**Comment by djay** [comment]
no much different from https://github.com/collective/plone.importexport/issues/55
