### ISSUE TITLE
Export story 4 - Export all sports related news

### ISSUE THREAD

**Issue by ironmaniiith** [collective/plone.importexport#58]
**Description**
As an admin I can go to site setup, filter out the all the **news** based on a **specific word** that’s present in its **description**. I can obtain all these pages as a zip along with CSV metadata

Demo video: [link](https://drive.google.com/open?id=1ud0G-YLDJn0dhFJiafKIgg3ggm-x9t-M)

![image](https://user-images.githubusercontent.com/9266422/60281236-31813580-9922-11e9-8287-c33a8ff2210d.png)

**Comment by djay** [comment]
similar to https://github.com/collective/plone.importexport/issues/55
