### ISSUE TITLE
Export story 5 - Export all files and images without preserving relative path

### ISSUE THREAD

**Issue by ironmaniiith** [collective/plone.importexport#59]
Description:

As an admin I can go to site setup, download a zip file which contains all the **images** and **files** present in my site. I am only interested in the content and **not the path where the content is present**, hence I should have a way in which I can export content **without preserving the relative path**. Since I only want the files, I don't expect a CSV metadata file in the downloaded zip

Demo vide: [link](https://drive.google.com/open?id=1AxvQtpvwQyY1BnDRctIlulc1fQG3Dew5)

Screenshot:
![image](https://user-images.githubusercontent.com/9266422/60282903-9d18d200-9925-11e9-848f-ae5fe260043b.png)

![image](https://user-images.githubusercontent.com/9266422/60282443-9a69ad00-9924-11e9-87ff-d98d21e47213.png)

**Comment by djay** [comment]
I don't really understand this feature/usecase. Is the idea that you flatten the blobs in the zip? for what reason? I think if you really want that you can do it after by unzipping and changing the data
