### ISSUE TITLE
Export story 8 - Export all the data that was created before a particular date

### ISSUE THREAD

**Issue by ironmaniiith** [collective/plone.importexport#62]
Description:

As an admin I can go to site setup and export all the data **that was created before a particular date** so that I can take a **backup** of all the contents in the site which were created before that date

Demo video: [link](https://drive.google.com/open?id=1ya0ytXy92xyV-uji9q9bBcMWAFwaGV_D)

Screenshot: 
![image](https://user-images.githubusercontent.com/9266422/60284258-bb340180-9928-11e9-9812-50b0fb988ea8.png)

**Comment by djay** [comment]
not different enough from https://github.com/collective/plone.importexport/issues/55
