### ISSUE TITLE
Export story 9 - Export only the description and the title of all the events that have ended

### ISSUE THREAD

**Issue by ironmaniiith** [collective/plone.importexport#63]
Description:

As an admin I can go to site setup and **export the description and title** of all the **events that have been completed** so that I can keep a track of what all events happened in the past and publish it on my personal website as **Past Events**

Demo video: [link](https://drive.google.com/open?id=1ZlKnp9aOZEq9ONHM_dzA-gM8JmSF5ir_)

Screenshot:
![image](https://user-images.githubusercontent.com/9266422/60284764-fedb3b00-9929-11e9-9e75-8e5d314223b4.png)

![image](https://user-images.githubusercontent.com/9266422/60284920-5d081e00-992a-11e9-83e2-b7450e931b25.png)

**Comment by djay** [comment]
already covered by #55
