### ISSUE TITLE
Export story 10 - Export all contents present in a particular folder with its metadata

### ISSUE THREAD

**Issue by ironmaniiith** [collective/plone.importexport#64]
**Description**:

As an admin I can go to site setup and **export all the contents** which is present in a **particular folder** which contains all the information related to a particular category.

Demo video: [link](https://drive.google.com/open?id=13Y6BX-G4q-IrzeWL9XVbozen34XV8Tiy)
Screenshot:

![image](https://user-images.githubusercontent.com/9266422/60286835-03a1ee00-992e-11e9-9234-0c3f945291a8.png)

**Comment by djay** [comment]
Not that much different from https://github.com/collective/plone.importexport/issues/55
